sudo: required

services:
  - docker

before_install:
  - docker build -t ronaldreeggan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ronaldreeggan/docker-react npm run test -- --coverage